# Generated by Django 3.0.2 on 2020-02-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complain_message',
            field=models.CharField(max_length=500),
        ),
    ]
