# Generated by Django 3.0.2 on 2020-02-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_auto_20191226_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number_1',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number_2',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number_3',
            field=models.CharField(max_length=11),
        ),
    ]
